In [4]:
import numpy as np

In [5]:
#Import test function
from test import test

In [6]:
# load data
# you need to change this path with your own directory
path = 'C:/Users/catia/Dropbox (UFL)/Teaching/2020 Fall/EEE 4773 Fundamentals of Machine Learning/GitHub/Final-Project/Code and Reports/Dataset/'

X_train = np.load(path+'data_training.npy',allow_pickle=True).astype('float')
y_train = np.load(path+'labels_training.npy')

X_test = np.load(path+'data_test.npy',allow_pickle=True).astype('float')
y_test = np.load(path+'labels_test.npy')

X_hardtest = np.load(path+'data_hardtest.npy',allow_pickle=True).astype('float')
y_hardtest = np.load(path+'labels_hardtest.npy')

X_train.shape, y_train.shape, X_test.shape, y_test.shape, X_hardtest.shape, y_hardtest.shape

((2400, 100000), (2400,), (640, 100000), (640,), (340, 100000), (340,))

In [7]:
score, cm ,final_pred, _ = test(X_train, y_train)

print('Accuracy score is: ', score)
print('Confusion Matrix: \n', cm)
print('Predicted labels: \n', final_pred)

C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator PCA from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your

Accuracy score is:  1.0
Confusion Matrix: 
 [[300   0   0   0   0   0   0   0]
 [  0 300   0   0   0   0   0   0]
 [  0   0 300   0   0   0   0   0]
 [  0   0   0 300   0   0   0   0]
 [  0   0   0   0 300   0   0   0]
 [  0   0   0   0   0 300   0   0]
 [  0   0   0   0   0   0 300   0]
 [  0   0   0   0   0   0   0 300]]
Predicted labels: 
 [2. 3. 2. ... 1. 5. 7.]


In [8]:
score, cm ,final_pred, _ = test(X_test, y_test)

print('Accuracy score is: ', score)
print('Confusion Matrix: \n', cm)
print('Predicted labels: \n', final_pred)

C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator PCA from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your

Accuracy score is:  0.8515625
Confusion Matrix: 
 [[67 11  0  2  0  0  1  1]
 [ 8 64  0  2  0  0  0  1]
 [ 1  1 69  3  1  3  0  3]
 [ 1  3  0 72  3  1  1  0]
 [ 0  1  5  0 70  0  7 12]
 [ 0  0  1  0  1 74  1  2]
 [ 3  0  1  1  0  0 70  2]
 [ 0  0  4  0  5  2  0 59]]
Predicted labels: 
 [7. 3. 6. 4. 7. 1. 1. 5. 7. 6. 4. 6. 3. 7. 7. 7. 4. 5. 8. 2. 2. 2. 4. 4.
 8. 3. 4. 1. 3. 7. 8. 1. 7. 2. 2. 6. 6. 6. 4. 1. 7. 8. 4. 5. 1. 8. 7. 7.
 8. 3. 2. 4. 7. 5. 4. 3. 4. 4. 6. 1. 6. 7. 1. 8. 4. 3. 5. 1. 4. 1. 6. 3.
 2. 5. 6. 6. 1. 3. 6. 2. 1. 5. 2. 5. 2. 2. 8. 4. 8. 5. 8. 2. 8. 5. 3. 8.
 4. 5. 4. 2. 4. 3. 4. 3. 5. 1. 1. 1. 6. 3. 6. 5. 3. 3. 2. 5. 4. 4. 6. 4.
 7. 1. 1. 1. 8. 4. 8. 1. 2. 2. 2. 7. 8. 6. 5. 6. 4. 3. 1. 6. 7. 2. 5. 8.
 1. 2. 6. 8. 1. 7. 6. 1. 5. 7. 6. 7. 2. 4. 3. 3. 4. 4. 3. 8. 1. 2. 3. 2.
 2. 6. 6. 8. 8. 3. 5. 3. 5. 8. 1. 7. 7. 3. 7. 6. 7. 8. 5. 1. 5. 5. 6. 5.
 4. 8. 4. 7. 2. 6. 3. 7. 6. 2. 7. 3. 6. 1. 4. 4. 7. 2. 3. 3. 4. 8. 3. 5.
 7. 6. 1. 5. 6. 3. 7. 2. 4. 5. 7. 2. 4. 8. 1. 5. 4. 6. 2

In [9]:
score, cm ,final_pred, _ = test(X_hardtest, y_hardtest)

print('Accuracy score is: ', score)
print('Confusion Matrix: \n', cm)
print('Predicted labels: \n', final_pred)

C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator PCA from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\catia\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your

Accuracy score is:  0.7441176470588236
Confusion Matrix: 
 [[ 0  0  0  0  0  0  0  0  0]
 [ 1 65 11  0  0  0  1  0  3]
 [ 2  7 61  0  0  0  1  0  1]
 [ 2  1  0  0  0  0  2  0  2]
 [ 4  2  2  0  0  0  1  0  2]
 [ 8  0  1  0  0  0  2  0 13]
 [ 2  0  1  0  0  0 70  0  1]
 [ 1  4  4  0  0  0  1  0  1]
 [ 0  1  0  0  0  0  2  0 57]]
Predicted labels: 
 [5. 7. 2. 6. 2. 1. 8. 7. 6. 6. 1. 1. 6. 2. 2. 6. 2. 8. 2. 1. 5. 8. 2. 1.
 8. 1. 8. 1. 6. 8. 8. 6. 6. 8. 7. 1. 1. 6. 8. 6. 8. 1. 6. 3. 2. 1. 1. 1.
 3. 6. 8. 6. 7. 1. 7. 2. 6. 1. 6. 1. 2. 8. 1. 2. 2. 5. 4. 6. 2. 8. 2. 1.
 2. 4. 4. 1. 8. 1. 1. 8. 2. 2. 1. 2. 8. 6. 6. 5. 6. 8. 6. 2. 8. 1. 8. 8.
 1. 2. 1. 2. 1. 6. 2. 6. 1. 2. 6. 2. 8. 1. 1. 2. 6. 8. 1. 2. 2. 5. 5. 2.
 8. 1. 1. 6. 8. 1. 8. 8. 8. 8. 1. 1. 7. 8. 8. 8. 2. 6. 6. 8. 6. 1. 2. 1.
 6. 2. 6. 2. 1. 1. 1. 8. 4. 6. 3. 2. 2. 3. 1. 4. 4. 8. 8. 1. 1. 8. 5. 6.
 2. 2. 4. 6. 5. 6. 1. 8. 2. 6. 1. 5. 1. 6. 1. 2. 8. 2. 6. 2. 1. 8. 2. 1.
 3. 1. 2. 8. 8. 2. 8. 2. 1. 3. 8. 6. 6. 8. 6. 2. 2. 1. 2. 5. 2. 2.